module MediaBookInfo
	BOOKS = 
	['book', 'Publisher Resources for the Lazy and Incompetent', 'Jules Sheridan Nogah', "Meh fixie mustache chia selvage. Actually af vegan la croix, helvetica hot chicken unicorn green juice cardigan live-edge wolf before they sold out four dollar toast narwhal blue bottle. Offal hammock craft beer, cold-pressed fam hell of swag edison bulb twee freegan tofu gluten-free farm-to-table shoreditch cornhole. Try-hard cred church-key thundercats flannel fingerstache, hoodie next level live-edge. Master cleanse tumeric hashtag whatever iceland semiotics. Tattooed succulents man braid, sustainable locavore gochujang farm-to-table. Wayfarers glossier distillery, try-hard thundercats vinyl vexillologist mlkshk sustainable banh mi poutine butcher crucifix tote bag pop-up."],
	['book', 'Ear-splitting Volume Crushers', 'Jawdat Kefilwe Nur', "Four dollar toast wolf blog literally asymmetrical, actually health goth. Four loko tumeric DIY 3 wolf moon, authentic prism thundercats synth paleo. Tote bag slow-carb air plant edison bulb, live-edge tacos stumptown drinking vinegar tousled af artisan DIY. Lo-fi slow-carb subway tile flannel cardigan, ugh disrupt. Organic crucifix four loko cray butcher. Polaroid fap hella kickstarter cronut. Vape church-key sriracha direct trade."],
	['book', 'Energy-draining, Soup-slurping Fools', 'Rama Hoshi', "Narwhal next level put a bird on it leggings scenester. Mustache sriracha tacos try-hard, narwhal organic hashtag woke crucifix butcher migas. Skateboard prism synth, kale chips crucifix post-ironic hammock af green juice deep v poutine etsy drinking vinegar echo park retro. Sartorial gastropub brooklyn, butcher activated charcoal biodiesel live-edge tumeric tote bag direct trade bespoke knausgaard. Craft beer viral health goth, microdosing locavore fixie cliche 8-bit tbh unicorn pour-over poutine. Hexagon pork belly drinking vinegar, knausgaard schlitz austin pok pok single-origin coffee shabby chic keffiyeh bitters echo park tousled intelligentsia gastropub. Quinoa tote bag woke mlkshk chambray, paleo marfa fap cornhole tumeric raw denim everyday carry lo-fi."],
	['book', 'Crisply-fried Walrus Hearts', 'Guo Tristen Harper', "Farm-to-table offal irony coloring book, small batch you probably haven't heard of them cliche leggings meditation. Hoodie man braid heirloom lyft, viral dreamcatcher polaroid letterpress subway tile tilde plaid poke next level ethical fashion axe. Etsy four dollar toast brunch small batch hell of. Cardigan vegan readymade cold-pressed, irony sriracha semiotics man braid enamel pin letterpress. Plaid hella austin fashion axe 3 wolf moon. Butcher keffiyeh pinterest, vinyl dreamcatcher master cleanse pop-up poke crucifix selfies letterpress drinking vinegar you probably haven't heard of them. Tumblr prism hot chicken, 3 wolf moon tumeric letterpress microdosing sriracha tote bag."],
	['book', 'Organic Raw Brioche', 'Grey Cruz Dara', "Retro glossier letterpress, subway tile coloring book 8-bit selfies semiotics VHS. Artisan humblebrag pitchfork plaid knausgaard, put a bird on it seitan slow-carb microdosing pork belly. Tbh etsy you probably haven't heard of them, selvage trust fund church-key semiotics ennui poke. Pour-over next level hot chicken pitchfork vape, kombucha schlitz bitters banjo messenger bag wayfarers jianbing mixtape post-ironic. Pour-over forage cardigan farm-to-table enamel pin, knausgaard single-origin coffee unicorn wolf VHS you probably haven't heard of them air plant etsy. Bitters live-edge fashion axe whatever. Distillery literally blue bottle affogato listicle disrupt."],
	['book', 'Savory Dry-aged Salmon', 'Roman Timo', "Ramps single-origin coffee affogato paleo wayfarers franzen. Pinterest actually offal, man braid trust fund tbh tofu tote bag hashtag af. Tattooed iPhone bespoke retro. Kitsch disrupt coloring book distillery, chartreuse hoodie edison bulb bushwick fam raclette slow-carb pork belly. Health goth try-hard raw denim, vape synth gochujang 8-bit helvetica banjo thundercats. Bushwick keytar butcher, shabby chic hexagon pabst health goth mumblecore. Gastropub la croix meggings, drinking vinegar everyday carry knausgaard put a bird on it pickled man bun craft beer banh mi williamsburg scenester."],
	['book', 'Horizonal Tidy Surfaces', 'Philippus Asse', "Cray try-hard tousled kinfolk, small batch live-edge raw denim. Vinyl narwhal swag, pork belly gastropub quinoa beard la croix succulents typewriter. Sriracha occupy poutine meh, pinterest crucifix succulents fingerstache typewriter tumblr. Sriracha cray bespoke ethical dreamcatcher ugh. Woke knausgaard pok pok asymmetrical. Authentic deep v lo-fi, hella pitchfork tumblr kale chips offal tbh hell of skateboard taxidermy church-key cold-pressed mustache. Poke single-origin coffee plaid godard."],
	['book', 'Gut-busting Pickled Cake', 'Amna Audra', "Food truck mustache sartorial, actually whatever art party you probably haven't heard of them pickled. Snackwave try-hard chillwave, fingerstache knausgaard meggings subway tile you probably haven't heard of them thundercats taxidermy waistcoat lumbersexual sartorial salvia synth. Microdosing kitsch truffaut, butcher dreamcatcher air plant blog craft beer vape unicorn hot chicken literally YOLO hell of. Gochujang polaroid try-hard, blue bottle ethical selvage letterpress. Everyday carry tote bag meggings flannel hella wayfarers etsy. Jean shorts meditation pok pok dreamcatcher crucifix fam occupy. Keffiyeh PBR&B asymmetrical, ramps chia ennui farm-to-table sartorial post-ironic."]
	end
